apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: cel-listener-interceptor
spec:
  serviceAccountName: pipeline
  triggers:
    - name: cel-trig-with-matches
      interceptors:
        - cel:
            filter: >-
              header.match('Event-Promoter-Checker-Com', 'webhook') &&
              header.canonical('x-secret-token').compareSecret('token', 'mysecret')
      bindings:
      - ref: pipeline-binding
      template:
        name: trigger-task-template
