apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: el-cel-listener-interceptor
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-cel-listener-interceptor
    weight: 100
  wildcardPolicy: None
  tls:
    termination: edge
