# Default values for promotionChecker.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image:
  repository: quay.io/nissessenap/promotionchecker
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.3.0"

config:
  artifactoryURL: http://test-promotion-test-promotion-checker:8081
  artifactoryAPIkey: ""
  artifactoryUSER: ""
  pollTime: 10
  httpTimeout: 3
  httpInsecure: true
  webhookSecret: test-secret
  dbType: memDB
  # endpointPort is missing under cm, it uses service.port. This to make it inpossible to mix up the config

containers:
  - repo: repo1
    image: app1
    webhook: http://el-cel-listener-interceptor:8080/webhook
  - repo: repo2
    image: app2
    webhook: http://el-cel-listener-interceptor:8080/webhook

metrics:
  enabled: true

service:
  type: ClusterIP
  port: 9090

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}
